name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: Runner_Assignment6
    steps:
      - name: Install Node.js and npm
        run: apk add nodejs npm
        
      - name: Install Docker
        run: apk add docker

      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: abuia/ikt206g24v06

      - name: Build and push Docker image
        uses:  docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: abuia/ikt206g24v06:latest

